services:
  - type: web
    name: laravel-api
    env: php
    buildCommand: |
      composer install
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        value: base64:Tn40/8Pdx0X9lk50WvCsVEllS0V2VpNNjQFVgXnARuU=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: HNGstage0
      - key: DB_USERNAME
        value: yroot
      - key: DB_PASSWORD
        value: yroot
